# Generated by Django 3.2 on 2021-04-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210414_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='unlike',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
