# Generated by Django 3.2 on 2021-04-14 09:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_userspostslikes_userspostsunlikes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userspostslikes',
            unique_together={('user', 'post')},
        ),
    ]
