# Generated by Django 3.2 on 2021-04-14 10:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_alter_userspostslikes_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userspostsunlikes',
            unique_together={('user', 'post')},
        ),
    ]
