# Generated by Django 3.2 on 2021-04-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_userspostsunlikes_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspostslikes',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
