# Generated by Django 3.2 on 2021-04-16 09:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_auto_20210416_0906'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPosts',
            new_name='UsersPosts',
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
        migrations.AlterModelTable(
            name='userspostslikes',
            table='likes',
        ),
        migrations.AlterModelTable(
            name='userspostsunlikes',
            table='unlikes',
        ),
    ]
